# ============================================================
# config/totem_right.conf
# 右半分 (Peripheral) 固有の設定
# ============================================================

# 右は常に Peripheral
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y

# PMW3610 センサー
# CONFIG_SPI=y
# CONFIG_INPUT=y
# CONFIG_ZMK_MOUSE=y

# 省電力モード
CONFIG_PM_DEVICE=y
