# ============================================================
# config/totem_right.conf
# 右半分 (Peripheral) 固有の設定
# ============================================================

# 右は常に Peripheral
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
# 右側も BLE 接続を有効にする
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=n

# --- Peripheral 側は Studio に接続しない ---
CONFIG_ZMK_STUDIO=n

# --- BLE Split 通信のみ ---
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y
CONFIG_ZMK_SPLIT_BLE=y

# --- バッテリー報告を有効化 ---
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ADC=y

# CONFIG_ZMK_BATTERY_VOLTAGE_DIVIDER=y
# CONFIG_ZMK_BATTERY_VOLTAGE_DIVIDER_FULL=2
# CONFIG_ZMK_BATTERY_VOLTAGE_DIVIDER_OUTPUT=1
# CONFIG_ZMK_BATTERY_ADC_CHANNEL=0
